version: "3.8"
services:
  bookdb:
    image: postgres
  rabbitmq:
    image: rabbitmq:3.9.8-management
  book.api:
    image: book_api_image
    build:
      context: .
      dockerfile: Libraries/Book/PhoneBook.Libraries.Book.Api/Dockerfile
volumes:
  bookdb_volume:
